### ISSUE TITLE
Dependency error?

### ISSUE THREAD

**Issue by picosam** [evenchange4/react-progressive-bg-image#81]
I get the following when I use `yarn add` any package:
`warning " > react-progressive-bg-image@2.1.3" has incorrect peer dependency "styled-components@^2.1.0".
[4/4] 📃  Building fresh packages...`

**Comment by evenchange4** [comment]
Upgrade to styled-components v3 and remove peer dependency via #82. 😀

Close it. Please feel free to reopen this issue if the problem still occurs with a newer version (`react-progressive-bg-image ^3.0.0`).
